FROM tensorflow/tensorflow:2.3.0

WORKDIR /usr/src/app

COPY code /usr/src/app/code
COPY Distributed_vgg16-2/EDGE /usr/src/app/models/EDGE
COPY Distributed_vgg16-2/FOG /usr/src/app/models/FOG
COPY Distributed_vgg16-2/CLOUD /usr/src/app/models/CLOUD

RUN pip install --upgrade pip
COPY requirements.txt /usr/src/app/requirements.txt
RUN pip install -r /usr/src/app/requirements.txt

CMD python code/main.py --tensorflow --models /usr/src/app/models/EDGE /usr/src/app/models/FOG /usr/src/app/models/CLOUD --name $GROUP_ID --producer-back $PRODUCER_BACK --producer-back-topic $PRODUCER_BACK_TOPIC --consumer-back $CONSUMER_BACK --consumer-back-topic $CONSUMER_BACK_TOPIC
