apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: kafka-2
  name: kafka-2-pod
spec:
  containers:
  - env:
    - name: HOSTNAME_COMMAND
      value: hostname
    - name: KAFKA_ADVERTISED_LISTENERS
      value: INSIDE://kafka-cluster-2:9092,OUTSIDE://192.168.0.101:9095
    - name: KAFKA_BROKER_ID
      value: "2"
    - name: KAFKA_CREATE_TOPICS
      # value: clouddevice:8:1,cloudedge:8:1,devicecloud:8:1,edgecloud:8:1 # TOPICS KAFKA-CLOUD
      # value: edgedevice:1:1,deviceedge:1:1 # TOPICS KAFKA-EDGE  1 Partition
      # value: edgedevice:2:1,deviceedge:2:1 # TOPICS KAFKA-EDGE  2 Partition
      # value: edgedevice:4:1,deviceedge:4:1 # TOPICS KAFKA-EDGE  4 Partition
      value: edgedevice:8:1,deviceedge:8:1 # TOPICS KAFKA-EDGE  8 Partition
      # value: edgedevice:10:1,deviceedge:10:1 # TOPICS KAFKA-EDGE  10 Partition
    - name: KAFKA_DEFAULT_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: INSIDE
    - name: KAFKA_LISTENERS
      value: INSIDE://:9092,OUTSIDE://:9095
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    - name: KAFKA_LOG_RETENTION_BYTES
      value: "-1"
    - name: KAFKA_LOG_RETENTION_DAYS
      value: "2"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
      value: "36000"
    - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
      value: "1048576999"
    - name: KAFKA_MESSAGE_MAX_BYTES
      value: "1024000000"
    image: wurstmeister/kafka:2.12-2.2.1
    name: kafka-2-pod
    ports:
    - containerPort: 9092
    resources: {}
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
