apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka-2
  name: kafka-cluster-2
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  # KAFKA 2
  - name: "9095"
    port: 9095
    targetPort: 9095
  selector:
    io.kompose.service: kafka-2
  type: LoadBalancer
status:
  loadBalancer: {}
